version: '2'
services:
  web:
    container_name: apache
    build: docker/apache2/
    environment:
      PHP_XDEBUG_ENABLED: 1
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ./source:/var/www/html
    networks:
      smartnet:
        ipv4_address: 172.16.0.10
  db:
    container_name: mysql
    build: docker/mysql/
    ports:
      - 3306:3306
    networks:
      smartnet:
        ipv4_address: 172.16.0.11
networks:
  smartnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1